### ISSUE TITLE
Spawn height

### ISSUE THREAD

**Issue by Jim1120** [Mka0207/DayZ-Bed-Respawning#1]
Hello,
I see that you have fixed the height of the spawn but I have just tested in several ways and I always spawn on the roof of the building where the bed is placed.
Do you have an idea ?
Thanks in advance !

**Comment by Mka0207** [comment]
Please reread the description on the workshop page : https://steamcommunity.com/sharedfiles/filedetails/?id=2111275052

Step 2.5 will fix this issue for you!

**Comment by Mka0207** [comment]
> 
> 
> Hello,
> I see that you have fixed the height of the spawn but I have just tested in several ways and I always spawn on the roof of the building where the bed is placed.
> Do you have an idea ?
> Thanks in advance !

Please reread the description on the workshop page : https://steamcommunity.com/sharedfiles/filedetails/?id=2111275052

Step 2 will fix this issue for you!

**Comment by Jim1120** [comment]
Yep, Thanks for the explanation !

**Comment by Mka0207** [comment]
> 
> 
> Yep, Thanks for the explanation !

Just pushed another update, be sure to reread the description!
