### ISSUE TITLE
Suggestion and permission

### ISSUE THREAD

**Issue by Mateuus** [Mka0207/DayZ-Bed-Respawning#2]
Hello, can you add for when a player puts a new bed delete or Old Bed Object?

Would you give me permission to add this function and add Respawn to a Type Menu (Spawn Select) ?

**Comment by Mateuus** [comment]
Sorry I just saw that you already made the first option.

**Comment by Mka0207** [comment]
I'd prefer if no edits were done, should be able to call the class tho if you want to make use of the functions!
